compile:
	GOOS=linux GOARCH=amd64 go build -o bin/linux/amd64/coinmon-go main.go
	GOOS=linux GOARCH=arm64 go build -o bin/linux/arm64/coinmon-go main.go
	GOOS=darwin GOARCH=amd64 go build -o bin/osx/amd64/coinmon-go main.go
	GOOS=darwin GOARCH=arm64 go build -o bin/osx/arm64/coinmon-go main.go
	GOOS=windows GOARCH=amd64 go build -o bin/windows/x64/coinmon-go.exe main.go
